//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBot.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResultMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResultMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TBot.Application.Resources.ResultMessage", typeof(ResultMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже зарегистрированы!.
        /// </summary>
        internal static string AccountAlreadyExists {
            get {
                return ResourceManager.GetString("AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры были сохранены..
        /// </summary>
        internal static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет доступа..
        /// </summary>
        internal static string DontHaveAccess {
            get {
                return ResourceManager.GetString("DontHaveAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка: .
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл успешно загружен на сервер..
        /// </summary>
        internal static string FileHaveBeenUploaded {
            get {
                return ResourceManager.GetString("FileHaveBeenUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузок не было..
        /// </summary>
        internal static string HistoryEmpty {
            get {
                return ResourceManager.GetString("HistoryEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные отсутствуют..
        /// </summary>
        internal static string noData {
            get {
                return ResourceManager.GetString("noData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не верный..
        /// </summary>
        internal static string PasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("PasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка регистрации.
        /// </summary>
        internal static string RegisterError {
            get {
                return ResourceManager.GetString("RegisterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо за регистрацию..
        /// </summary>
        internal static string ThanksForRegister {
            get {
                return ResourceManager.GetString("ThanksForRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при загрузке файла..
        /// </summary>
        internal static string UploadFileError {
            get {
                return ResourceManager.GetString("UploadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет пользователя с таким Id..
        /// </summary>
        internal static string UserIsNotExistWithId {
            get {
                return ResourceManager.GetString("UserIsNotExistWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роль пользователя успешно изменена на .
        /// </summary>
        internal static string UserRoleIHaveBeenChanged {
            get {
                return ResourceManager.GetString("UserRoleIHaveBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный пароль или имя..
        /// </summary>
        internal static string wrongNameOrPassword {
            get {
                return ResourceManager.GetString("wrongNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверные параметры..
        /// </summary>
        internal static string WrongParameters {
            get {
                return ResourceManager.GetString("WrongParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы авторизованы..
        /// </summary>
        internal static string YouAreAuthorized {
            get {
                return ResourceManager.GetString("YouAreAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не зарегистрированы..
        /// </summary>
        internal static string YouNotRegisted {
            get {
                return ResourceManager.GetString("YouNotRegisted", resourceCulture);
            }
        }
    }
}
